name: Build MOSHPIT Docker image

on:
  workflow_dispatch:
    inputs:
      imageTags:
        description: 'Tags for the Docker image being built.'
        required: true
        type: string
      qiimeVersion:
        description: 'QIIME release version.'
        required: true
        type: string
      baseImageTag:
        description: 'Base image tag.'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to the remote registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ inputs.imageTags }}
        build-args: |
          BASE_IMAGE_TAG=${{ inputs.baseImageTag }}
          VERSION=${{ inputs.qiimeVersion }}
