name: Build MOSHPIT Docker image

on:
  workflow_dispatch:
    inputs:
      imageTags:
        description: 'Tags for the Docker image being built.'
        required: true
        type: string
      epoch:
        description: 'Current QIIME 2 epoch.'
        required: true
        type: string
      distro:
        description: 'Distribution to be used in the image.'
        required: true
        type: string
      environment:
        description: 'Environment: passed (for weekly builds), released (for production).'
        required: true
        type: string
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to the remote registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ inputs.imageTags }}
        build-args: |
          EPOCH=${{ inputs.epoch }}
          DISTRO=${{ inputs.distro }}
          ENVIRONMENT=${{ inputs.environment }}
