name: Build q2-shotgun Docker image

on:
  workflow_dispatch:
    inputs:
      imageTags:
        description: 'Tags for the Docker image being built.'
        required: true
        type: string
      qiimeVersion:
        description: 'qiime2'
        required: true
        type: string
      typesVersion:
        description: 'q2-types-genomics-version'
        required: false
        type: string
      assemblyVersion:
        description: 'q2-assembly version'
        required: false
        type: string
      moshpitVersion:
        description: 'q2-moshpit version'
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check available space
      run: df -h

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ inputs.imageTags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          QIIME_VERSION=${{ inputs.qiimeVersion }}
          TYPES_VERSION=${{ inputs.typesVersion }}
          ASSEMBLY_VERSION=${{ inputs.assemblyVersion }}
          MOSHPIT_VERSION=${{ inputs.moshpitVersion }}
